### ISSUE TITLE
Accounts are still trying to invite friends [send friend request to each other] even tho its i tried to disable it? Bug?

### ISSUE THREAD

**Issue by Glass47** [CSTraders/bot-idle#36]
Hello. I've deployed the said code into docker and it seems to be working flawlessly, however i came into message/annoyance where when i start the stack i still get this response for each of my account that i farm hours on, even tho i removed the code so it should be disabled

```
[Username] Account limitations:

 - limited account (see https://support.steampowered.com/kb_article.php?ref=3330-IAGK-7663)

 - cannot invite friends
```

and this is for every single account i've added

My bot.json config is structured like this

```{
  "username": "Username",
  "password": "Pass",
  "app_ids": [Gameid],
  "persona": 3
}

```

My docker-compose[Stack] in Portainer is this

```version: '3'

services:
  bot-idle:
    image: ghcr.io/cstraders/bot-idle
    volumes:
      - /root/steam-configs:/bots
      - /root/steam-configs/bot1.json:/steam-configs/bot1.json
      - /root/steam-configs/bot2.json:/steam-configs/bot2.json
      - /root/steam-configs/bot3.json:/steam-configs/bot3.json
      - /root/steam-configs/bot4.json:/steam-configs/bot4.json
      - /root/steam-configs/bot5.json:/steam-configs/bot5.json
      - /root/steam-configs/bot6.json:/steam-configs/bot6.json
      - /root/steam-configs/bot7.json:/steam-configs/bot7.json
      - /root/steam-configs/bot8.json:/steam-configs/bot8.json
      - /root/steam-configs/bot9.json:/steam-configs/bot9.json
      - /root/steam-configs/bot10.json:/steam-configs/bot10.json
    environment:
      - BOT_CONFIG_DIR=/bots
      - BOT_CONFIG_1=/steam-configs/bot1.json
      - BOT_CONFIG_2=/steam-configs/bot2.json
      - BOT_CONFIG_3=/steam-configs/bot3.json
      - BOT_CONFIG_4=/steam-configs/bot4.json
      - BOT_CONFIG_5=/steam-configs/bot5.json
      - BOT_CONFIG_6=/steam-configs/bot6.json
      - BOT_CONFIG_7=/steam-configs/bot7.json
      - BOT_CONFIG_8=/steam-configs/bot8.json
      - BOT_CONFIG_9=/steam-configs/bot9.json
      - BOT_CONFIG_10=/steam-configs/bot10.json
      - BOT_APP_IDS=gameid
      - BOT_PERSONA=3
    restart: always
```

Since i run 10 accounts as a test. However it's kinda annoying me to see that i get an error saying that accounts can't add others, does that mean the request has been sent to Steam servers and accounts tried to add each other? Even tho i removed that part of config thus it should be disabled? Correct me if i am wrong, let me know if i need to add the BOT_ADD_FRIENDS somewhere, either in Docker-Compose[Stack] or in each of bot.json configs. Thank you and great project! 

Reason why i am somewhat concerned about this is, if i scale this to 100 or 1000 steam accounts and when i start them all, i might get blocked by steam for sending "Friend request" requests/attempts to their api/server, so i am wondering if that will be issue. That's why i want to disable so bots don't even try to add each other to begin with.

**Comment by Glass47** [comment]
Just tagging you @kldzj because i assume you were involved in creation of this and might have useful info.

**Comment by kldzj** [comment]
Hi @Glass47,

The warning you mention is not coming from the `add friends` feature. It's just a general hint about your account limitations that's logged once the account has logged in. 😊

Hope that helps. If you have any further questions let me know.

**Comment by kldzj** [comment]
By the way, you should be able to simplify your `docker-compose.yml` like this:

```yaml
services:
  bot-idle:
    image: ghcr.io/cstraders/bot-idle
    volumes:
      - /root/steam-configs:/bots
    environment:
      - BOT_CONFIG_DIR=/bots
      - BOT_APP_IDS=gameid
      - BOT_PERSONA=3
    restart: always
```

If you specify the `BOT_CONFIG_DIR` variable the tool will try to load all the json files contained in that directory.

**Comment by Glass47** [comment]
> By the way, you should be able to simplify your `docker-compose.yml` like this:
> 
> ```yaml
> services:
>   bot-idle:
>     image: ghcr.io/cstraders/bot-idle
>     volumes:
>       - /root/steam-configs:/bots
>     environment:
>       - BOT_CONFIG_DIR=/bots
>       - BOT_APP_IDS=gameid
>       - BOT_PERSONA=3
>     restart: always
> ```
> 
> If you specify the `BOT_CONFIG_DIR` variable the tool will try to load all the json files contained in that directory.


I highly appreciate your answer, thank you for the tip which will make my life definitely easier.
Regarding `BOT_APP_IDS=gameid` If i want to add multiple games do i need to just put , ?
Example `BOT_APP_IDS=1234,1235,1236` Does it need to have comma after the last id? so like this `BOT_APP_IDS=1234,1235,1236,` or just `BOT_APP_IDS=1234,1235,1236` and that's it?

**Comment by Glass47** [comment]
> @Glass47 correct, you comma separate the game IDs, but do not add a comma at the end 😊
> 
> Make sure not to add too many game IDs though.

Thank you for reply. I am at best going to farm 2 or 3 games. For now i just need 1 game with actual hours, and second game is going to be dead one called Empires. That way i could maybe see if all 20/20 of my accounts are online and farming. And also know if the accounts count towards "Online players" aka "Players right now" and if they do count, then i know i could technically bot some game and add 5 or 10k fake players just to try and push it into higher ranking and thus try to revive the game.  Anyways, at the end of the day, main reason is to farm hours, however i am also curious about if it increases online player count.

**Comment by kldzj** [comment]
> however i am also curious about if it increases online player count.

That I'm not too sure about, you'd have to try. Be careful though as Steam might not like it if you overdo it. :P

**Comment by Glass47** [comment]
> > however i am also curious about if it increases online player count.
> 
> That I'm not too sure about, you'd have to try. Be careful though as Steam might not like it if you overdo it. :P

Thanks for quick replies, as always, wish you the best and sorry if i interrupted you, if you want i can tip you few bucks, you can send me Paypal or Litecoin/Solana wallet. Best regards!

**Comment by kldzj** [comment]
No problem at all. Thanks for the kindness, but don't worry about tips, knowing that this helps you is enough for me. 😊
